from __future__ import annotations

from typing import Any, Mapping


def _string(value: Any) -> str:
    return str(value or "")


def build_streaming_mode_input(preset: Mapping[str, Any]) -> dict[str, str]:
    # NOTE: PVE_THIN_CLIENT_PRESET_BEAGLE_* env var keys are kept for thin-client
    # backwards compatibility — renaming them would break deployed thin clients.
    # The returned dict keys use beagle_ prefixes for new internal consumers.
    return {
        "moonlight_host": _string(preset.get("PVE_THIN_CLIENT_PRESET_MOONLIGHT_HOST")),
        "spice_url": _string(preset.get("PVE_THIN_CLIENT_PRESET_SPICE_URL")),
        # beagle_host/node/vmid are the current names; beagle_* aliases kept for compat
        "beagle_host": _string(preset.get("PVE_THIN_CLIENT_PRESET_BEAGLE_HOST")),
        "beagle_node": _string(preset.get("PVE_THIN_CLIENT_PRESET_BEAGLE_NODE")),
        "beagle_vmid": _string(preset.get("PVE_THIN_CLIENT_PRESET_BEAGLE_VMID")),
        "spice_username": _string(preset.get("PVE_THIN_CLIENT_PRESET_SPICE_USERNAME")),
        "spice_password": _string(preset.get("PVE_THIN_CLIENT_PRESET_SPICE_PASSWORD")),
        "beagle_username": _string(preset.get("PVE_THIN_CLIENT_PRESET_BEAGLE_USERNAME")),
        "beagle_password": _string(preset.get("PVE_THIN_CLIENT_PRESET_BEAGLE_PASSWORD")),
        "novnc_url": _string(preset.get("PVE_THIN_CLIENT_PRESET_NOVNC_URL")),
        "dcv_url": _string(preset.get("PVE_THIN_CLIENT_PRESET_DCV_URL")),
    }


def build_runtime_extension_fields(
    *,
    network_static_address: str = "",
    network_static_prefix: str = "24",
    network_gateway: str = "",
    network_dns_servers: str = "1.1.1.1 8.8.8.8",
    beagle_manager_pinned_pubkey: str = "",
    beagle_enrollment_url: str = "",
    beagle_manager_token: str = "",
    beagle_enrollment_token: str = "",
    thinclient_password: str = "",
    beagle_update_enabled: str = "1",
    beagle_update_channel: str = "stable",
    beagle_update_behavior: str = "prompt",
    beagle_update_feed_url: str = "",
    beagle_update_version_pin: str = "",
    beagle_egress_mode: str = "full",
    beagle_egress_type: str = "wireguard",
    beagle_egress_interface: str = "wg-beagle",
    beagle_egress_domains: str = "",
    beagle_egress_resolvers: str = "1.1.1.1 8.8.8.8",
    beagle_egress_allowed_ips: str = "",
    beagle_egress_wg_address: str = "",
    beagle_egress_wg_dns: str = "",
    beagle_egress_wg_public_key: str = "",
    beagle_egress_wg_endpoint: str = "",
    beagle_egress_wg_persistent_keepalive: str = "25",
    beagle_egress_wg_private_key: str = "",
    beagle_egress_wg_preshared_key: str = "",
    identity_hostname: str = "",
    identity_timezone: str = "",
    identity_locale: str = "",
    identity_keymap: str = "",
    identity_chrome_profile: str = "default",
    moonlight_port: str = "",
    sunshine_pinned_pubkey: str = "",
    sunshine_server_name: str = "",
    sunshine_server_stream_port: str = "",
    sunshine_server_uniqueid: str = "",
    sunshine_server_cert_b64: str = "",
) -> dict[str, str]:
    return {
        "PVE_THIN_CLIENT_PRESET_NETWORK_STATIC_ADDRESS": _string(network_static_address),
        "PVE_THIN_CLIENT_PRESET_NETWORK_STATIC_PREFIX": _string(network_static_prefix),
        "PVE_THIN_CLIENT_PRESET_NETWORK_GATEWAY": _string(network_gateway),
        "PVE_THIN_CLIENT_PRESET_NETWORK_DNS_SERVERS": _string(network_dns_servers),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_MANAGER_PINNED_PUBKEY": _string(beagle_manager_pinned_pubkey),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_ENROLLMENT_URL": _string(beagle_enrollment_url),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_MANAGER_TOKEN": _string(beagle_manager_token),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_ENROLLMENT_TOKEN": _string(beagle_enrollment_token),
        "PVE_THIN_CLIENT_PRESET_THINCLIENT_PASSWORD": _string(thinclient_password),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_UPDATE_ENABLED": _string(beagle_update_enabled),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_UPDATE_CHANNEL": _string(beagle_update_channel),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_UPDATE_BEHAVIOR": _string(beagle_update_behavior),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_UPDATE_FEED_URL": _string(beagle_update_feed_url),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_UPDATE_VERSION_PIN": _string(beagle_update_version_pin),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_EGRESS_MODE": _string(beagle_egress_mode),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_EGRESS_TYPE": _string(beagle_egress_type),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_EGRESS_INTERFACE": _string(beagle_egress_interface),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_EGRESS_DOMAINS": _string(beagle_egress_domains),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_EGRESS_RESOLVERS": _string(beagle_egress_resolvers),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_EGRESS_ALLOWED_IPS": _string(beagle_egress_allowed_ips),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_EGRESS_WG_ADDRESS": _string(beagle_egress_wg_address),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_EGRESS_WG_DNS": _string(beagle_egress_wg_dns),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_EGRESS_WG_PUBLIC_KEY": _string(beagle_egress_wg_public_key),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_EGRESS_WG_ENDPOINT": _string(beagle_egress_wg_endpoint),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_EGRESS_WG_PERSISTENT_KEEPALIVE": _string(
            beagle_egress_wg_persistent_keepalive
        ),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_EGRESS_WG_PRIVATE_KEY": _string(beagle_egress_wg_private_key),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_EGRESS_WG_PRESHARED_KEY": _string(beagle_egress_wg_preshared_key),
        "PVE_THIN_CLIENT_PRESET_IDENTITY_HOSTNAME": _string(identity_hostname),
        "PVE_THIN_CLIENT_PRESET_IDENTITY_TIMEZONE": _string(identity_timezone),
        "PVE_THIN_CLIENT_PRESET_IDENTITY_LOCALE": _string(identity_locale),
        "PVE_THIN_CLIENT_PRESET_IDENTITY_KEYMAP": _string(identity_keymap),
        "PVE_THIN_CLIENT_PRESET_IDENTITY_CHROME_PROFILE": _string(identity_chrome_profile),
        "PVE_THIN_CLIENT_PRESET_MOONLIGHT_PORT": _string(moonlight_port),
        "PVE_THIN_CLIENT_PRESET_SUNSHINE_PINNED_PUBKEY": _string(sunshine_pinned_pubkey),
        "PVE_THIN_CLIENT_PRESET_SUNSHINE_SERVER_NAME": _string(sunshine_server_name),
        "PVE_THIN_CLIENT_PRESET_SUNSHINE_SERVER_STREAM_PORT": _string(sunshine_server_stream_port),
        "PVE_THIN_CLIENT_PRESET_SUNSHINE_SERVER_UNIQUEID": _string(sunshine_server_uniqueid),
        "PVE_THIN_CLIENT_PRESET_SUNSHINE_SERVER_CERT_B64": _string(sunshine_server_cert_b64),
    }


def build_common_preset(
    *,
    profile_name: str,
    vm_name: str,
    hostname_value: str,
    autostart: str,
    default_mode: str,
    network_mode: str,
    network_interface: str,
    # Beagle-native host binding fields.
    beagle_scheme: str = "",
    beagle_host: str = "",
    beagle_port: str = "",
    beagle_node: str = "",
    beagle_vmid: str = "",
    beagle_realm: str = "",
    beagle_verify_tls: str = "",
    beagle_manager_url: str = "",
    moonlight_host: str,
    moonlight_local_host: str,
    moonlight_app: str,
    moonlight_bin: str,
    moonlight_resolution: str,
    moonlight_fps: str,
    moonlight_bitrate: str,
    moonlight_video_codec: str,
    moonlight_video_decoder: str,
    moonlight_audio_config: str,
    moonlight_absolute_mouse: str,
    moonlight_quit_after: str,
    sunshine_api_url: str,
    sunshine_username: str,
    sunshine_password: str,
    sunshine_pin: str,
    extra_fields: Mapping[str, Any] | None = None,
) -> dict[str, str]:
    preset = {
        "PVE_THIN_CLIENT_PRESET_PROFILE_NAME": _string(profile_name),
        "PVE_THIN_CLIENT_PRESET_VM_NAME": _string(vm_name),
        "PVE_THIN_CLIENT_PRESET_HOSTNAME_VALUE": _string(hostname_value),
        "PVE_THIN_CLIENT_PRESET_AUTOSTART": _string(autostart),
        "PVE_THIN_CLIENT_PRESET_DEFAULT_MODE": _string(default_mode),
        "PVE_THIN_CLIENT_PRESET_NETWORK_MODE": _string(network_mode),
        "PVE_THIN_CLIENT_PRESET_NETWORK_INTERFACE": _string(network_interface),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_SCHEME": _string(beagle_scheme),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_HOST": _string(beagle_host),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_PORT": _string(beagle_port),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_NODE": _string(beagle_node),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_VMID": _string(beagle_vmid),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_REALM": _string(beagle_realm),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_VERIFY_TLS": _string(beagle_verify_tls),
        "PVE_THIN_CLIENT_PRESET_BEAGLE_USERNAME": "",
        "PVE_THIN_CLIENT_PRESET_BEAGLE_PASSWORD": "",
        "PVE_THIN_CLIENT_PRESET_BEAGLE_TOKEN": "",
        "PVE_THIN_CLIENT_PRESET_BEAGLE_MANAGER_URL": _string(beagle_manager_url),
        "PVE_THIN_CLIENT_PRESET_SPICE_METHOD": "",
        "PVE_THIN_CLIENT_PRESET_SPICE_URL": "",
        "PVE_THIN_CLIENT_PRESET_SPICE_USERNAME": "",
        "PVE_THIN_CLIENT_PRESET_SPICE_PASSWORD": "",
        "PVE_THIN_CLIENT_PRESET_SPICE_TOKEN": "",
        "PVE_THIN_CLIENT_PRESET_NOVNC_URL": "",
        "PVE_THIN_CLIENT_PRESET_NOVNC_USERNAME": "",
        "PVE_THIN_CLIENT_PRESET_NOVNC_PASSWORD": "",
        "PVE_THIN_CLIENT_PRESET_NOVNC_TOKEN": "",
        "PVE_THIN_CLIENT_PRESET_DCV_URL": "",
        "PVE_THIN_CLIENT_PRESET_DCV_USERNAME": "",
        "PVE_THIN_CLIENT_PRESET_DCV_PASSWORD": "",
        "PVE_THIN_CLIENT_PRESET_DCV_TOKEN": "",
        "PVE_THIN_CLIENT_PRESET_DCV_SESSION": "",
        "PVE_THIN_CLIENT_PRESET_MOONLIGHT_HOST": _string(moonlight_host),
        "PVE_THIN_CLIENT_PRESET_MOONLIGHT_LOCAL_HOST": _string(moonlight_local_host),
        "PVE_THIN_CLIENT_PRESET_MOONLIGHT_APP": _string(moonlight_app),
        "PVE_THIN_CLIENT_PRESET_MOONLIGHT_BIN": _string(moonlight_bin),
        "PVE_THIN_CLIENT_PRESET_MOONLIGHT_RESOLUTION": _string(moonlight_resolution),
        "PVE_THIN_CLIENT_PRESET_MOONLIGHT_FPS": _string(moonlight_fps),
        "PVE_THIN_CLIENT_PRESET_MOONLIGHT_BITRATE": _string(moonlight_bitrate),
        "PVE_THIN_CLIENT_PRESET_MOONLIGHT_VIDEO_CODEC": _string(moonlight_video_codec),
        "PVE_THIN_CLIENT_PRESET_MOONLIGHT_VIDEO_DECODER": _string(moonlight_video_decoder),
        "PVE_THIN_CLIENT_PRESET_MOONLIGHT_AUDIO_CONFIG": _string(moonlight_audio_config),
        "PVE_THIN_CLIENT_PRESET_MOONLIGHT_ABSOLUTE_MOUSE": _string(moonlight_absolute_mouse),
        "PVE_THIN_CLIENT_PRESET_MOONLIGHT_QUIT_AFTER": _string(moonlight_quit_after),
        "PVE_THIN_CLIENT_PRESET_SUNSHINE_API_URL": _string(sunshine_api_url),
        "PVE_THIN_CLIENT_PRESET_SUNSHINE_USERNAME": _string(sunshine_username),
        "PVE_THIN_CLIENT_PRESET_SUNSHINE_PASSWORD": _string(sunshine_password),
        "PVE_THIN_CLIENT_PRESET_SUNSHINE_PIN": _string(sunshine_pin),
        "PVE_THIN_CLIENT_PRESET_SUNSHINE_SERVER_NAME": "",
        "PVE_THIN_CLIENT_PRESET_SUNSHINE_SERVER_STREAM_PORT": "",
        "PVE_THIN_CLIENT_PRESET_SUNSHINE_SERVER_UNIQUEID": "",
        "PVE_THIN_CLIENT_PRESET_SUNSHINE_SERVER_CERT_B64": "",
    }
    if extra_fields:
        for key, value in extra_fields.items():
            preset[str(key)] = _string(value)
    return preset
