#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="${1:-/etc/pve-thin-client}"

MODE="${MODE:-SPICE}"
RUNTIME_USER="${RUNTIME_USER:-thinclient}"
AUTOSTART="${AUTOSTART:-1}"
PROFILE_NAME="${PROFILE_NAME:-default}"
HOSTNAME_VALUE="${HOSTNAME_VALUE:-pve-thin-client}"
CONNECTION_METHOD="${CONNECTION_METHOD:-direct}"
SPICE_URL="${SPICE_URL:-}"
NOVNC_URL="${NOVNC_URL:-}"
DCV_URL="${DCV_URL:-}"
REMOTE_VIEWER_BIN="${REMOTE_VIEWER_BIN:-remote-viewer}"
BROWSER_BIN="${BROWSER_BIN:-chromium}"
BROWSER_FLAGS="${BROWSER_FLAGS:---kiosk --incognito --no-first-run --disable-session-crashed-bubble}"
DCV_VIEWER_BIN="${DCV_VIEWER_BIN:-dcvviewer}"
PROXMOX_SCHEME="${PROXMOX_SCHEME:-https}"
PROXMOX_HOST="${PROXMOX_HOST:-}"
PROXMOX_PORT="${PROXMOX_PORT:-8006}"
PROXMOX_NODE="${PROXMOX_NODE:-}"
PROXMOX_VMID="${PROXMOX_VMID:-}"
PROXMOX_REALM="${PROXMOX_REALM:-pam}"
PROXMOX_VERIFY_TLS="${PROXMOX_VERIFY_TLS:-0}"
NETWORK_MODE="${NETWORK_MODE:-dhcp}"
NETWORK_INTERFACE="${NETWORK_INTERFACE:-}"
NETWORK_STATIC_ADDRESS="${NETWORK_STATIC_ADDRESS:-}"
NETWORK_STATIC_PREFIX="${NETWORK_STATIC_PREFIX:-24}"
NETWORK_GATEWAY="${NETWORK_GATEWAY:-}"
NETWORK_DNS_SERVERS="${NETWORK_DNS_SERVERS:-1.1.1.1 8.8.8.8}"
CONNECTION_USERNAME="${CONNECTION_USERNAME:-}"
CONNECTION_PASSWORD="${CONNECTION_PASSWORD:-}"
CONNECTION_TOKEN="${CONNECTION_TOKEN:-}"

install -d -m 0755 "$CONFIG_DIR"

cat > "$CONFIG_DIR/thinclient.conf" <<EOF
# pve-thin-client runtime configuration
PVE_THIN_CLIENT_MODE="$MODE"
PVE_THIN_CLIENT_RUNTIME_USER="$RUNTIME_USER"
PVE_THIN_CLIENT_AUTOSTART="$AUTOSTART"
PVE_THIN_CLIENT_PROFILE_NAME="$PROFILE_NAME"
PVE_THIN_CLIENT_HOSTNAME="$HOSTNAME_VALUE"
PVE_THIN_CLIENT_CONNECTION_METHOD="$CONNECTION_METHOD"
PVE_THIN_CLIENT_SPICE_URL="$SPICE_URL"
PVE_THIN_CLIENT_REMOTE_VIEWER_BIN="$REMOTE_VIEWER_BIN"
PVE_THIN_CLIENT_NOVNC_URL="$NOVNC_URL"
PVE_THIN_CLIENT_BROWSER_BIN="$BROWSER_BIN"
PVE_THIN_CLIENT_BROWSER_FLAGS="$BROWSER_FLAGS"
PVE_THIN_CLIENT_DCV_URL="$DCV_URL"
PVE_THIN_CLIENT_DCV_VIEWER_BIN="$DCV_VIEWER_BIN"
PVE_THIN_CLIENT_PROXMOX_SCHEME="$PROXMOX_SCHEME"
PVE_THIN_CLIENT_PROXMOX_HOST="$PROXMOX_HOST"
PVE_THIN_CLIENT_PROXMOX_PORT="$PROXMOX_PORT"
PVE_THIN_CLIENT_PROXMOX_NODE="$PROXMOX_NODE"
PVE_THIN_CLIENT_PROXMOX_VMID="$PROXMOX_VMID"
PVE_THIN_CLIENT_PROXMOX_REALM="$PROXMOX_REALM"
PVE_THIN_CLIENT_PROXMOX_VERIFY_TLS="$PROXMOX_VERIFY_TLS"
EOF

cat > "$CONFIG_DIR/network.env" <<EOF
PVE_THIN_CLIENT_NETWORK_MODE="$NETWORK_MODE"
PVE_THIN_CLIENT_NETWORK_INTERFACE="$NETWORK_INTERFACE"
PVE_THIN_CLIENT_NETWORK_STATIC_ADDRESS="$NETWORK_STATIC_ADDRESS"
PVE_THIN_CLIENT_NETWORK_STATIC_PREFIX="$NETWORK_STATIC_PREFIX"
PVE_THIN_CLIENT_NETWORK_GATEWAY="$NETWORK_GATEWAY"
PVE_THIN_CLIENT_NETWORK_DNS_SERVERS="$NETWORK_DNS_SERVERS"
EOF

cat > "$CONFIG_DIR/credentials.env" <<EOF
PVE_THIN_CLIENT_CONNECTION_USERNAME="$CONNECTION_USERNAME"
PVE_THIN_CLIENT_CONNECTION_PASSWORD="$CONNECTION_PASSWORD"
PVE_THIN_CLIENT_CONNECTION_TOKEN="$CONNECTION_TOKEN"
EOF

chmod 0644 "$CONFIG_DIR/thinclient.conf" "$CONFIG_DIR/network.env"
chmod 0600 "$CONFIG_DIR/credentials.env"
