#!/usr/bin/env python3
"""Generate a lightweight OpenAPI v1 schema from route literals.

The generator scans `beagle-host/**/*.py` for `/api/v1/*` path strings and
produces a conservative OpenAPI document plus a coverage report.
"""

from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HOST_DIR = ROOT / "beagle-host"
OPENAPI_OUT = ROOT / "docs" / "api" / "openapi.v1.generated.yaml"
COVERAGE_OUT = ROOT / "docs" / "api" / "openapi-v1-coverage.md"


PATH_RE = re.compile(r"([\"'])(/api/v1(?:/[A-Za-z0-9._{}\-]+)*)\1")
METHOD_HINT_RE = re.compile(r"handles_(get|post|put|delete|patch)\s*\(")


def normalize_path(path: str) -> str:
    # Keep named path parameters as-is and avoid replacing plain substrings
    # inside static route segments (e.g. "bridges").
    normalized = path.replace("//", "/")
    return normalized


def discover_paths() -> dict[str, set[str]]:
    methods_by_path: dict[str, set[str]] = defaultdict(set)
    for source in HOST_DIR.rglob("*.py"):
        text = source.read_text(encoding="utf-8", errors="ignore")
        lines = text.splitlines()
        for index, line in enumerate(lines):
            for _, match_path in PATH_RE.findall(line):
                if not match_path.startswith("/api/v1"):
                    continue
                path = normalize_path(match_path)
                context = "\n".join(lines[max(0, index - 6) : index + 7]).lower()
                hinted = set(METHOD_HINT_RE.findall(context))
                if "route_post" in context:
                    hinted.add("post")
                if "route_get" in context:
                    hinted.add("get")
                if "route_put" in context:
                    hinted.add("put")
                if "route_delete" in context:
                    hinted.add("delete")
                if not hinted:
                    hinted = {"get"}
                methods_by_path[path].update(hinted)
    return methods_by_path


def operation_id(method: str, path: str) -> str:
    suffix = re.sub(r"[^A-Za-z0-9]+", "_", path).strip("_")
    return f"{method}_{suffix}".lower()


def path_parameters(path: str) -> list[str]:
    return re.findall(r"\{([A-Za-z0-9_]+)\}", path)


def emit_openapi(paths: dict[str, set[str]]) -> str:
    lines: list[str] = []
    lines.extend(
        [
            "openapi: 3.0.3",
            "info:",
            "  title: Beagle Control Plane API (generated)",
            "  version: v1-generated",
            "  description: Generated from route literals in beagle-host code.",
            "servers:",
            "  - url: https://beagle-server",
            "paths:",
        ]
    )
    for path in sorted(paths):
        lines.append(f"  {path}:")
        for method in sorted(paths[path]):
            lines.append(f"    {method}:")
            lines.append(f"      operationId: {operation_id(method, path)}")
            lines.append("      responses:")
            lines.append("        '200':")
            lines.append("          description: Success")
            params = path_parameters(path)
            if params:
                lines.append("      parameters:")
                for param in params:
                    lines.append(f"        - name: {param}")
                    lines.append("          in: path")
                    lines.append("          required: true")
                    lines.append("          schema:")
                    lines.append("            type: string")
    return "\n".join(lines) + "\n"


def emit_coverage(paths: dict[str, set[str]]) -> str:
    lines: list[str] = []
    lines.append("# OpenAPI v1 Coverage (Generated)")
    lines.append("")
    lines.append("Generated by `scripts/generate-openapi-v1.py`.")
    lines.append("")
    lines.append(f"- Discovered path count: {len(paths)}")
    lines.append("")
    lines.append("## Discovered Paths")
    lines.append("")
    for path in sorted(paths):
        methods = ", ".join(sorted(paths[path]))
        lines.append(f"- `{path}` ({methods})")
    lines.append("")
    lines.append("## Notes")
    lines.append("")
    lines.append("- This generator uses static string scanning and method hints from surrounding code.")
    lines.append("- Dynamic/composed routes should be reviewed manually.")
    lines.append("- Unknown/partial method hints default to GET and should be corrected by maintainers.")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    paths = discover_paths()
    OPENAPI_OUT.parent.mkdir(parents=True, exist_ok=True)
    OPENAPI_OUT.write_text(emit_openapi(paths), encoding="utf-8")
    COVERAGE_OUT.write_text(emit_coverage(paths), encoding="utf-8")
    print(f"wrote {OPENAPI_OUT}")
    print(f"wrote {COVERAGE_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
