#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_DIR="${INSTALL_DIR:-/opt/beagle}"
VERSION="$(tr -d ' \n\r' < "$ROOT_DIR/VERSION")"
SERVER_NAME="${PVE_DCV_PROXY_SERVER_NAME:-$(hostname -f 2>/dev/null || hostname)}"
LISTEN_PORT="${PVE_DCV_PROXY_LISTEN_PORT:-8443}"
SITE_PORT="${BEAGLE_SITE_PORT:-443}"
DOWNLOADS_PATH="${PVE_DCV_DOWNLOADS_PATH:-/beagle-downloads}"
DOWNLOADS_BASE_URL="${PVE_DCV_DOWNLOADS_BASE_URL:-https://${SERVER_NAME}:${LISTEN_PORT}${DOWNLOADS_PATH}}"
PUBLIC_UPDATE_BASE_URL="${BEAGLE_PUBLIC_UPDATE_BASE_URL:-https://beagle-os.com/beagle-updates}"
DEFAULT_USB_INSTALLER_URL="https://{host}:${LISTEN_PORT}/beagle-api/api/v1/vms/{vmid}/installer.sh"
USB_INSTALLER_URL="${PVE_DCV_USB_INSTALLER_URL:-$DEFAULT_USB_INSTALLER_URL}"
CONFIG_DIR="${PVE_DCV_CONFIG_DIR:-/etc/beagle}"
WEB_UI_TITLE="${BEAGLE_WEB_UI_TITLE:-Beagle OS Web UI}"
BEAGLE_WEB_UI_TRUSTED_API_ORIGINS="${BEAGLE_WEB_UI_TRUSTED_API_ORIGINS:-}"
BEAGLE_WEB_UI_ALLOW_HASH_TOKEN="${BEAGLE_WEB_UI_ALLOW_HASH_TOKEN:-0}"
BEAGLE_WEB_UI_ALLOW_ABSOLUTE_API_TARGETS="${BEAGLE_WEB_UI_ALLOW_ABSOLUTE_API_TARGETS:-0}"
BEAGLE_WEB_UI_SEND_LEGACY_API_TOKEN_HEADER="${BEAGLE_WEB_UI_SEND_LEGACY_API_TOKEN_HEADER:-0}"
BEAGLE_WEB_UI_ALLOW_INSECURE_EXTERNAL_URLS="${BEAGLE_WEB_UI_ALLOW_INSECURE_EXTERNAL_URLS:-0}"
BEAGLE_HOST_PROVIDER="${BEAGLE_HOST_PROVIDER:-beagle}"
BEAGLE_SERVER_INSTALL_MODE="${BEAGLE_SERVER_INSTALL_MODE:-standalone}"
BEAGLE_HOST_TLS_CERT_FILE="${BEAGLE_HOST_TLS_CERT_FILE:-}"
BEAGLE_HOST_TLS_KEY_FILE="${BEAGLE_HOST_TLS_KEY_FILE:-}"
DEFAULT_PROXMOX_USERNAME="${PVE_THIN_CLIENT_DEFAULT_PROXMOX_USERNAME:-${PVE_DCV_PROXMOX_USERNAME:-}}"
DEFAULT_PROXMOX_PASSWORD="${PVE_THIN_CLIENT_DEFAULT_PROXMOX_PASSWORD:-${PVE_DCV_PROXMOX_PASSWORD:-}}"
DEFAULT_PROXMOX_TOKEN="${PVE_THIN_CLIENT_DEFAULT_PROXMOX_TOKEN:-${PVE_DCV_PROXMOX_TOKEN:-}}"
BEAGLE_AUTH_BOOTSTRAP_USERNAME="${BEAGLE_AUTH_BOOTSTRAP_USERNAME:-admin}"
BEAGLE_AUTH_BOOTSTRAP_PASSWORD="${BEAGLE_AUTH_BOOTSTRAP_PASSWORD:-}"
BEAGLE_AUTH_BOOTSTRAP_DISABLE="${BEAGLE_AUTH_BOOTSTRAP_DISABLE:-0}"

write_host_env_file() {
  install -d -m 0755 "$CONFIG_DIR"
  cat > "$CONFIG_DIR/host.env" <<EOF
INSTALL_DIR="$INSTALL_DIR"
PVE_DCV_PROXY_SERVER_NAME="$SERVER_NAME"
PVE_DCV_PROXY_LISTEN_PORT="$LISTEN_PORT"
BEAGLE_SITE_PORT="$SITE_PORT"
BEAGLE_WEB_UI_URL="${BEAGLE_WEB_UI_URL:-https://$SERVER_NAME}"
BEAGLE_WEB_UI_TITLE="$WEB_UI_TITLE"
BEAGLE_WEB_UI_TRUSTED_API_ORIGINS="$BEAGLE_WEB_UI_TRUSTED_API_ORIGINS"
BEAGLE_WEB_UI_ALLOW_HASH_TOKEN="$BEAGLE_WEB_UI_ALLOW_HASH_TOKEN"
BEAGLE_WEB_UI_ALLOW_ABSOLUTE_API_TARGETS="$BEAGLE_WEB_UI_ALLOW_ABSOLUTE_API_TARGETS"
BEAGLE_WEB_UI_SEND_LEGACY_API_TOKEN_HEADER="$BEAGLE_WEB_UI_SEND_LEGACY_API_TOKEN_HEADER"
BEAGLE_WEB_UI_ALLOW_INSECURE_EXTERNAL_URLS="$BEAGLE_WEB_UI_ALLOW_INSECURE_EXTERNAL_URLS"
BEAGLE_HOST_PROVIDER="$BEAGLE_HOST_PROVIDER"
BEAGLE_SERVER_INSTALL_MODE="$BEAGLE_SERVER_INSTALL_MODE"
PVE_DCV_DOWNLOADS_PATH="$DOWNLOADS_PATH"
PVE_DCV_DOWNLOADS_BASE_URL="$DOWNLOADS_BASE_URL"
BEAGLE_PUBLIC_UPDATE_BASE_URL="$PUBLIC_UPDATE_BASE_URL"
PVE_DCV_USB_INSTALLER_URL="$USB_INSTALLER_URL"
PVE_DCV_CONFIG_DIR="$CONFIG_DIR"
BEAGLE_HOST_TLS_CERT_FILE="$BEAGLE_HOST_TLS_CERT_FILE"
BEAGLE_HOST_TLS_KEY_FILE="$BEAGLE_HOST_TLS_KEY_FILE"
EOF

  cat > "$CONFIG_DIR/credentials.env" <<EOF
PVE_THIN_CLIENT_DEFAULT_PROXMOX_USERNAME="$DEFAULT_PROXMOX_USERNAME"
PVE_THIN_CLIENT_DEFAULT_PROXMOX_PASSWORD="$DEFAULT_PROXMOX_PASSWORD"
PVE_THIN_CLIENT_DEFAULT_PROXMOX_TOKEN="$DEFAULT_PROXMOX_TOKEN"
EOF
  chmod 0600 "$CONFIG_DIR/credentials.env"
}

write_host_env_file
BEAGLE_HOST_PROVIDER="$BEAGLE_HOST_PROVIDER" \
  BEAGLE_AUTH_BOOTSTRAP_USERNAME="$BEAGLE_AUTH_BOOTSTRAP_USERNAME" \
  BEAGLE_AUTH_BOOTSTRAP_PASSWORD="$BEAGLE_AUTH_BOOTSTRAP_PASSWORD" \
  BEAGLE_AUTH_BOOTSTRAP_DISABLE="$BEAGLE_AUTH_BOOTSTRAP_DISABLE" \
  "$INSTALL_DIR/scripts/install-beagle-host-services.sh"

PVE_DCV_PROXY_SERVER_NAME="$SERVER_NAME" \
  PVE_DCV_PROXY_LISTEN_PORT="$LISTEN_PORT" \
  BEAGLE_SITE_PORT="$SITE_PORT" \
  BEAGLE_WEB_UI_URL="${BEAGLE_WEB_UI_URL:-https://$SERVER_NAME}" \
  BEAGLE_WEB_UI_TITLE="$WEB_UI_TITLE" \
  PVE_DCV_DOWNLOADS_PATH="$DOWNLOADS_PATH" \
  PVE_DCV_DOWNLOADS_BASE_URL="$DOWNLOADS_BASE_URL" \
  PVE_DCV_PROXY_CERT_FILE="${BEAGLE_HOST_TLS_CERT_FILE:-}" \
  PVE_DCV_PROXY_KEY_FILE="${BEAGLE_HOST_TLS_KEY_FILE:-}" \
  "$INSTALL_DIR/scripts/install-beagle-proxy.sh"

echo "Post-install bootstrap complete in $INSTALL_DIR"
